version: 3.0.{build}

image:
- Visual Studio 2019

init:
  # Gather some basic build environment details.
  - rem set

environment:
  VCDIR: \Microsoft Visual Studio\2019\Community\VC
  QTDIR: C:\Qt\6.1.2\msvc2019_64  

configuration: release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - set ARCH=x64
  - set SETUPOUT=Launchy_Setup
  - set ISSO=SETUP.iss
  - if %QTDIR:_64=%==%QTDIR% set ARCH=x86
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%%VCDIR%\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul
  - if %ARCH%==x64 set ISSO=SETUP_x64.iss
  - if %ARCH%==x64 set SETUPOUT=Launchy_Setup_x64
  - choco install -y InnoSetup
  - set PATH=C:\Program Files (x86)\Inno Setup 5;%PATH%

before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%\launchy

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\launchy\win
  - buildTranslations.bat
  - xcopy /E /F /I /Y %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%\launchy\%CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER%\launchy\%CONFIGURATION%
  - windeployqt .
  - cd %APPVEYOR_BUILD_FOLDER%\launchy\win\installer
  - ISCC %ISSO%
  - cd %APPVEYOR_BUILD_FOLDER%\launchy\win\installer\%CONFIGURATION%\
  - echo ren %SETUPOUT%.exe %SETUPOUT%-%APPVEYOR_BUILD_VERSION%.exe
  - ren %SETUPOUT%.exe %SETUPOUT%-%APPVEYOR_BUILD_VERSION%.exe
  - dir %APPVEYOR_BUILD_FOLDER%\launchy\win\installer\%CONFIGURATION%\

artifacts:
  - path: launchy/win/installer/release/*.exe

build_script:
  - '%make%'

deploy:
  release: launchy-v$(appveyor_build_version)
  description: 'Launchy'
  provider: GitHub
  auth_token:
    secure: ovJS5y2wip9xPRPeETEpmphe+QX6PVHUnvYqy73OPGUTt+yEV5WdfRCFZDxWTBn/
  artifact: /.*Launchy_Setup*\.exe/
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only


# fetch repository as zip archive
shallow_clone: true
